// Code generated by goctl. DO NOT EDIT.
package types

type SimpleMsg struct {
	Message string `json:"msg,optional"`
}

type StandardMsg struct {
	Message          string `json:"msg,optional"`
	EncryptedMessage string `json:"encryptedMsg,optional"`
	DecryptedMessage string `json:"decryptedMsg,optional"`
}
